"use strict";
const V=["عجيزي","تفاحي","كلاماتا","منزانيلو","دولسي","بيكوال","صنف آخر"];let last=null;
const $=x=>document.getElementById(x), m=v=>new Intl.NumberFormat("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
document.addEventListener("DOMContentLoaded",()=>{if(!getToken()){location.href="../admin/login.html";return} add();$("add").onclick=add;$("f").onsubmit=save;$("full").onclick=()=>{$("paid").value=total().toFixed(2)};$("print").onclick=()=>last&&prt(last);$("new").onclick=()=>location.reload()});
function add(){const tr=document.createElement("tr");tr.innerHTML=`<td><select class="v">${V.map(x=>`<option>${x}</option>`).join("")}</select><input class="custom" placeholder="اسم الصنف" style="display:none;margin-top:5px"></td><td><input class="w" type="number" min=".001" step=".001" required></td><td><input class="p" type="number" min="0" step=".01" required></td><td class="t">0.00</td><td><button type="button" class="btn red del">×</button></td>`;$("lines").appendChild(tr);tr.querySelector(".v").onchange=e=>tr.querySelector(".custom").style.display=e.target.value==="صنف آخر"?"block":"none";tr.querySelectorAll(".w,.p").forEach(x=>x.oninput=calc);tr.querySelector(".del").onclick=()=>{if($("lines").children.length>1)tr.remove();calc()}}
function total(){return [...$("lines").children].reduce((s,r)=>s+Number(r.querySelector(".w").value||0)*Number(r.querySelector(".p").value||0),0)}
function calc(){[...$("lines").children].forEach(r=>r.querySelector(".t").textContent=m(Number(r.querySelector(".w").value||0)*Number(r.querySelector(".p").value||0)));$("grand").textContent=m(total())}
async function img(file){if(!file)return null;const im=await new Promise((ok,no)=>{const x=new Image;x.onload=()=>ok(x);x.onerror=no;x.src=URL.createObjectURL(file)}),sc=Math.min(1,1400/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=im.width*sc;c.height=im.height*sc;c.getContext("2d").drawImage(im,0,0,c.width,c.height);const d=c.toDataURL("image/jpeg",.72);URL.revokeObjectURL(im.src);return{fileName:(file.name||"image")+".jpg",mimeType:"image/jpeg",base64:d.split(",")[1]}}
async function save(e){e.preventDefault();$("save").disabled=true;try{const lines=[...$("lines").children].map(r=>{const sel=r.querySelector(".v").value;return{varietyName:sel==="صنف آخر"?r.querySelector(".custom").value.trim():sel,weightKg:Number(r.querySelector(".w").value),pricePerKg:Number(r.querySelector(".p").value)}});if(lines.some(x=>!x.varietyName||x.weightKg<=0||x.pricePerKg<0))throw Error("راجع الصنف والوزن والسعر");if(Number($("paid").value||0)>total()+.01)throw Error("المدفوع أكبر من الإجمالي");const a=[];const i=await img($("idcard").files[0]),d=await img($("doc").files[0]);if(i)a.push({...i,type:"ID_CARD"});if(d)a.push({...d,type:"RECEIPT"});const r=await apiPost("/olive/receipts",{companyId:Number(getCompanyId()||1),siteCode:$("siteCode").value,supplierName:$("supplierName").value,supplierPhone:$("supplierPhone").value,supplierNationalId:$("supplierNationalId").value,supplierAddress:$("supplierAddress").value,vehiclePlate:$("vehiclePlate").value,lines,paidAmount:Number($("paid").value||0),paymentMethod:$("method").value,paymentReference:$("ref").value,notes:$("notes").value,attachments:a});last=r.data||r;$("print").disabled=false;$("msg").innerHTML=`<div class="msg ok">تم الحفظ: ${last.receipt_no}</div>`}catch(x){console.error(x);$("msg").innerHTML=`<div class="msg err">${esc(x.message||"فشل الحفظ")}</div>`}finally{$("save").disabled=false}}
function prt(r){const w=window.open("","_blank","width=420,height=700");if(!w)return;w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>@page{size:80mm auto;margin:3mm}body{font-family:Arial;width:72mm;margin:auto;font-size:12px}h1,h2,p{text-align:center;margin:4px}.x{border-top:1px dashed #000;margin:7px 0}table{width:100%;font-size:10px}td{padding:2px}.tot{font-size:16px;font-weight:bold}</style></head><body><h1>VIRGINIA</h1><h2>إيصال استلام زيتون</h2><div class="x"></div><p>${esc(r.receipt_no)}</p><p>${new Date(r.created_at).toLocaleString("ar-EG")}</p><p>المورد: ${esc(r.supplier_name)}</p><div class="x"></div><table>${r.lines.map(x=>`<tr><td>${esc(x.variety_name)}</td><td>${x.weight_kg} كجم</td><td>${m(x.price_per_kg)}</td><td>${m(x.line_total)}</td></tr>`).join("")}</table><div class="x"></div><p class="tot">الإجمالي ${m(r.total_amount)} جنيه</p><p>المدفوع ${m(r.paid_amount)} | المتبقي ${m(r.balance_amount)}</p><p>المحاسب: ${esc(r.created_by||"-")}</p><br><p>توقيع المورد: ____________</p></body></html>`);w.document.close();setTimeout(()=>w.print(),200)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
