"use strict";
let catalog=[],printSettings=null,last=null;
const $=x=>document.getElementById(x),m=v=>new Intl.NumberFormat("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
document.addEventListener("DOMContentLoaded",async()=>{if(!getToken()){location.href="../admin/login.html";return}await Promise.all([loadCatalog(),loadPrint()]);add();$("add").onclick=add;$("f").onsubmit=save;$("full").onclick=()=>{$("paid").value=total().toFixed(2)};$("print").onclick=()=>last&&prt(last);$("new").onclick=()=>location.reload()});
async function loadCatalog(){const r=await apiGet("/olive/catalog",{companyId:Number(getCompanyId()||1)});catalog=(r.data||r).filter(x=>x.active)}
async function loadPrint(){const r=await apiGet("/olive/settings/receipt",{companyId:Number(getCompanyId()||1)});printSettings=r.data||r}
function options(){return `<option value="">اختر الصنف</option>`+catalog.map(x=>`<option value="${x.id}" data-price="${x.current_price??""}">${esc(x.name)}</option>`).join("")}
function add(){const tr=document.createElement("tr");tr.innerHTML=`<td><select class="v" required>${options()}</select></td><td><input class="w" type="number" min=".001" step=".001" required></td><td><input class="p" type="number" min="0" step=".01" required></td><td class="t">0.00</td><td><button type="button" class="btn red del">×</button></td>`;$("lines").appendChild(tr);tr.querySelector(".v").onchange=e=>{const o=e.target.selectedOptions[0],p=o?.dataset.price;tr.querySelector(".p").value=p===""?"":Number(p).toFixed(2);tr.dataset.catalogPrice=p;calc()};tr.querySelector(".p").oninput=()=>{const cp=tr.dataset.catalogPrice;tr.classList.toggle("override",cp!==undefined&&cp!==""&&Math.abs(Number(tr.querySelector(".p").value||0)-Number(cp))>.0001);calc()};tr.querySelector(".w").oninput=calc;tr.querySelector(".del").onclick=()=>{if($("lines").children.length>1)tr.remove();calc()}}
function total(){return [...$("lines").children].reduce((s,r)=>s+Number(r.querySelector(".w").value||0)*Number(r.querySelector(".p").value||0),0)}
function calc(){[...$("lines").children].forEach(r=>r.querySelector(".t").textContent=m(Number(r.querySelector(".w").value||0)*Number(r.querySelector(".p").value||0)));$("grand").textContent=m(total())}
async function img(file){if(!file)return null;const im=await new Promise((ok,no)=>{const x=new Image;x.onload=()=>ok(x);x.onerror=no;x.src=URL.createObjectURL(file)}),sc=Math.min(1,1400/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=im.width*sc;c.height=im.height*sc;c.getContext("2d").drawImage(im,0,0,c.width,c.height);const d=c.toDataURL("image/jpeg",.72);URL.revokeObjectURL(im.src);return{fileName:(file.name||"image")+".jpg",mimeType:"image/jpeg",base64:d.split(",")[1]}}
async function save(e){e.preventDefault();$("save").disabled=true;try{const lines=[...$("lines").children].map(r=>{const id=Number(r.querySelector(".v").value),c=catalog.find(x=>Number(x.id)===id);return{varietyId:id,varietyName:c?.name||"",weightKg:Number(r.querySelector(".w").value),pricePerKg:Number(r.querySelector(".p").value)}});if(lines.some(x=>!x.varietyId||!x.varietyName||x.weightKg<=0||x.pricePerKg<0))throw Error("راجع الصنف والوزن والسعر");if(Number($("paid").value||0)>total()+.01)throw Error("المدفوع أكبر من الإجمالي");const a=[];const i=await img($("idcard").files[0]),d=await img($("doc").files[0]);if(i)a.push({...i,type:"ID_CARD"});if(d)a.push({...d,type:"RECEIPT"});const r=await apiPost("/olive/receipts",{companyId:Number(getCompanyId()||1),siteCode:$("siteCode").value,supplierName:$("supplierName").value,supplierPhone:$("supplierPhone").value,supplierNationalId:$("supplierNationalId").value,supplierAddress:$("supplierAddress").value,vehiclePlate:$("vehiclePlate").value,lines,paidAmount:Number($("paid").value||0),paymentMethod:$("method").value,paymentReference:$("ref").value,notes:$("notes").value,attachments:a});last=r.data||r;$("print").disabled=false;$("msg").innerHTML=`<div class="msg ok">تم الحفظ: ${last.receipt_no}</div>`}catch(x){$("msg").innerHTML=`<div class="msg err">${esc(x.message||"فشل الحفظ")}</div>`}finally{$("save").disabled=false}}
function prt(r){const s=printSettings||{},width=Number(s.paper_width_mm||80),w=window.open("","_blank","width=440,height=760");if(!w)return;const logo=s.has_logo?`<img src="https://api.mi.virginiaolive.com/api/olive/settings/receipt/logo?companyId=${Number(getCompanyId()||1)}" style="max-width:55mm;max-height:22mm;display:block;margin:0 auto 4px">`:"";w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>@page{size:${width}mm auto;margin:3mm}body{font-family:Arial;width:${width-8}mm;margin:auto;font-size:12px}h1,h2,p{text-align:center;margin:4px}.x{border-top:1px dashed #000;margin:7px 0}table{width:100%;font-size:10px}td{padding:2px}.tot{font-size:16px;font-weight:bold}</style></head><body>${logo}<h1>${esc(s.company_name||"VIRGINIA")}</h1><h2>${esc(s.receipt_title||"إيصال استلام زيتون")}</h2>${s.company_address?`<p>${esc(s.company_address)}</p>`:""}${s.company_phone?`<p>${esc(s.company_phone)}</p>`:""}<div class="x"></div><p>${esc(r.receipt_no)}</p><p>${new Date(r.created_at).toLocaleString("ar-EG")}</p><p>المورد: ${esc(r.supplier_name)}</p>${s.show_supplier_phone&&r.supplier_phone?`<p>الهاتف: ${esc(r.supplier_phone)}</p>`:""}${s.show_supplier_national_id&&r.supplier_national_id?`<p>الرقم القومي: ${esc(r.supplier_national_id)}</p>`:""}${s.show_vehicle_plate&&r.vehicle_plate?`<p>السيارة: ${esc(r.vehicle_plate)}</p>`:""}<div class="x"></div><table>${r.lines.map(x=>`<tr><td>${esc(x.variety_name)}</td><td>${x.weight_kg} كجم</td><td>${m(x.price_per_kg)}</td><td>${m(x.line_total)}</td></tr>`).join("")}</table><div class="x"></div><p class="tot">الإجمالي ${m(r.total_amount)} جنيه</p><p>المدفوع ${m(r.paid_amount)} | المتبقي ${m(r.balance_amount)}</p><p>المحاسب: ${esc(r.created_by||"-")}</p>${s.footer_text?`<div class="x"></div><p>${esc(s.footer_text)}</p>`:""}<br><p>توقيع المورد: ____________</p></body></html>`);w.document.close();setTimeout(()=>w.print(),250)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
