"use strict";
const $=x=>document.getElementById(x), money=v=>new Intl.NumberFormat("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
let catalog=[];
document.addEventListener("DOMContentLoaded",()=>{if(!getToken()){location.href="../admin/login.html";return}$("addBtn").onclick=addVariety;$("savePrice").onclick=savePrice;$("closePrice").onclick=()=>$("priceModal").classList.remove("open");$("savePrint").onclick=savePrint;$("removeLogo").onclick=removeLogo;loadCatalog();loadPrint()});
async function loadCatalog(){try{const r=await apiGet("/olive/catalog",{companyId:Number(getCompanyId()||1)});catalog=r.data||r;render()}catch(e){message(e.message||"فشل تحميل الأصناف",true)}}
function render(){$("body").innerHTML=catalog.map(v=>`<tr><td><b>${esc(v.name)}</b><div style="font-size:11px;color:#777">${esc(v.code||"")}</div></td><td><span class="pill ${v.active?"":"off"}">${v.active?"فعال":"موقوف"}</span></td><td>${v.current_price==null?"—":money(v.current_price)}</td><td>${v.price_effective_from?new Date(v.price_effective_from).toLocaleString("ar-EG"):"—"}</td><td><button class="btn priceBtn" data-id="${v.id}">السعر/التاريخ</button> <button class="btn ${v.active?"red":"gray"} toggleBtn" data-id="${v.id}" data-active="${v.active}">${v.active?"إيقاف":"تفعيل"}</button></td></tr>`).join("");document.querySelectorAll(".priceBtn").forEach(b=>b.onclick=()=>openPrice(Number(b.dataset.id)));document.querySelectorAll(".toggleBtn").forEach(b=>b.onclick=()=>toggle(Number(b.dataset.id),b.dataset.active!=="true"))}
async function addVariety(){try{await apiPost("/olive/settings/varieties",{companyId:Number(getCompanyId()||1),name:$("name").value.trim(),code:$("code").value.trim()});$("name").value="";$("code").value="";await loadCatalog();message("تمت إضافة الصنف")}catch(e){message(e.message||"فشل الإضافة",true)}}
async function toggle(id,active){try{await apiPatch(`/olive/settings/varieties/${id}`,{companyId:Number(getCompanyId()||1),active});await loadCatalog()}catch(e){message(e.message||"فشل التعديل",true)}}
async function openPrice(id){const v=catalog.find(x=>Number(x.id)===id);$("varietyId").value=id;$("priceTitle").textContent=`السعر: ${v?.name||""}`;$("price").value=v?.current_price??"";const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("effectiveFrom").value=d.toISOString().slice(0,16);$("reason").value="";$("priceModal").classList.add("open");await loadHistory(id)}
async function loadHistory(id){const r=await apiGet(`/olive/settings/varieties/${id}/history`,{companyId:Number(getCompanyId()||1)}),rows=r.data||r;$("history").innerHTML=rows.map(x=>`<tr><td>${money(x.price_per_kg)}</td><td>${new Date(x.effective_from).toLocaleString("ar-EG")}</td><td>${x.effective_to?new Date(x.effective_to).toLocaleString("ar-EG"):"حتى الآن"}</td><td>${esc(x.change_reason||"")}</td><td>${esc(x.changed_by||"-")}</td></tr>`).join("")||`<tr><td colspan="5">لا يوجد تاريخ أسعار</td></tr>`}
async function savePrice(){try{const id=Number($("varietyId").value);await apiPost(`/olive/settings/varieties/${id}/prices`,{companyId:Number(getCompanyId()||1),pricePerKg:Number($("price").value),effectiveFrom:new Date($("effectiveFrom").value).toISOString(),changeReason:$("reason").value.trim()});await loadHistory(id);await loadCatalog();message("تم حفظ السعر الجديد")}catch(e){message(e.message||"فشل حفظ السعر",true)}}
async function loadPrint(){try{const r=await apiGet("/olive/settings/receipt",{companyId:Number(getCompanyId()||1)}),x=r.data||r;$("companyName").value=x.company_name||"VIRGINIA";$("receiptTitle").value=x.receipt_title||"إيصال استلام زيتون";$("companyAddress").value=x.company_address||"";$("companyPhone").value=x.company_phone||"";$("footerText").value=x.footer_text||"";$("paperWidth").value=String(x.paper_width_mm||80);$("showPhone").checked=x.show_supplier_phone!==false;$("showNationalId").checked=Boolean(x.show_supplier_national_id);$("showVehicle").checked=x.show_vehicle_plate!==false;if(x.has_logo){$("logoPreview").src=`${window.API_BASE_URL||"https://api.mi.virginiaolive.com/api"}/olive/settings/receipt/logo?companyId=${Number(getCompanyId()||1)}&t=${Date.now()}`;$("logoPreview").style.display="block"}}catch(e){message(e.message||"فشل تحميل إعدادات الفاتورة",true)}}
async function fileBase64(file){if(!file)return null;return await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(",")[1]);r.onerror=no;r.readAsDataURL(file)})}
async function savePrint(){try{const file=$("logoFile").files[0];await apiPut("/olive/settings/receipt",{companyId:Number(getCompanyId()||1),companyName:$("companyName").value.trim(),receiptTitle:$("receiptTitle").value.trim(),companyAddress:$("companyAddress").value.trim(),companyPhone:$("companyPhone").value.trim(),footerText:$("footerText").value.trim(),paperWidthMm:Number($("paperWidth").value),showSupplierPhone:$("showPhone").checked,showSupplierNationalId:$("showNationalId").checked,showVehiclePlate:$("showVehicle").checked,logoBase64:await fileBase64(file),logoMimeType:file?.type||null});message("تم حفظ تصميم الفاتورة");await loadPrint()}catch(e){message(e.message||"فشل حفظ تصميم الفاتورة",true)}}
async function removeLogo(){if(!confirm("حذف شعار الفاتورة؟"))return;try{await apiDelete("/olive/settings/receipt/logo",{companyId:Number(getCompanyId()||1)});$("logoPreview").style.display="none";$("logoPreview").removeAttribute("src");$("logoFile").value="";message("تم حذف الشعار")}catch(e){message(e.message||"فشل حذف الشعار",true)}}
function message(t,bad=false){$("msg").innerHTML=`<div style="padding:10px;border-radius:8px;margin:8px 0;background:${bad?"#fee2e2":"#dcfce7"}">${esc(t)}</div>`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
